#coding: UTF-8

module Ash
	module Disposition

		MAIN_DIR_ADAPTER = "#{MAIN_PATH}adapter#{File::SEPARATOR}"
		MAIN_DIR_ADAPTER_ROUTING = "#{MAIN_DIR_ADAPTER}routing#{File::SEPARATOR}"

		MAIN_DIR_INCLUDE = "#{MAIN_PATH}include#{File::SEPARATOR}"
		MAIN_DIR_INCLUDE_CONFIG = "#{MAIN_DIR_INCLUDE}config#{File::SEPARATOR}"
		MAIN_DIR_INCLUDE_CLASS = "#{MAIN_DIR_INCLUDE}class#{File::SEPARATOR}"
		MAIN_DIR_INCLUDE_FUNCTION = "#{MAIN_DIR_INCLUDE}function#{File::SEPARATOR}"

		MAIN_DIR_ASSETS = "#{MAIN_PATH}assets#{File::SEPARATOR}"
		MAIN_DIR_ASSETS_IMAGE = "#{MAIN_DIR_ASSETS}image#{File::SEPARATOR}"
		MAIN_DIR_ASSETS_CSS = "#{MAIN_DIR_ASSETS}css#{File::SEPARATOR}"
		MAIN_DIR_ASSETS_JS = "#{MAIN_DIR_ASSETS}js#{File::SEPARATOR}"
		MAIN_DIR_ASSETS_FONTS = "#{MAIN_DIR_ASSETS}fonts#{File::SEPARATOR}"

		MAIN_DIR_PLUGIN = "#{MAIN_PATH}plugin#{File::SEPARATOR}"

	end
end
